//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WEBthanh.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class BaiViett
    {
        public int MaBV { get; set; }
        public string TenBV { get; set; }
        public string Anh { get; set; }
        public Nullable<System.DateTime> NgayCapNhat { get; set; }
        public string Poster { get; set; }
        public string MoTa { get; set; }
    }
}
