//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WEBthanh.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class HinhAnhPhoto
    {
        public int MaHA { get; set; }
        public string Anh { get; set; }
        public string DiaDiem { get; set; }
        public Nullable<System.DateTime> NgayCapNhat { get; set; }
        public string Maker { get; set; }
    }
}
