//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WEBthanh.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class NGUOIDUNG
    {
        public int MaKH { get; set; }
        [Display(Name ="Họ tên")]
        [Required(ErrorMessage ="{0} chưa được nhập")]
        public string HoTen { get; set; }

        [Display(Name = "Tài khoản")]
        [Required(ErrorMessage = "{0} chưa được nhập")]
        public string TaiKhoan { get; set; }

        [Display(Name = "Mật khẩu")]
        [Required(ErrorMessage = "{0} chưa được nhập")]
        [DataType(DataType.Password)]
        public string MatKhau { get; set; }

        [Display(Name = "Email")]
        [Required(ErrorMessage = "{0} chưa được nhập")]
        public string Email { get; set; }


        [Display(Name = "Địa chỉ")]
        [Required(ErrorMessage = "{0} chưa được nhập")]
        public string DiaChi { get; set; }

        [Display(Name = "Phone")]
        [Required(ErrorMessage = "{0} chưa được nhập")]
        public string DienThoai { get; set; }

        [Display(Name = "Giới tính")]
        [Required(ErrorMessage = "{0} chưa được nhập")]
        public string GioiTinh { get; set; }

        [Display(Name = "Năm-tháng-ngày sinh (VD:1992-03-21)")]
        [Required(ErrorMessage = "{0} chưa được nhập")]
        public Nullable<System.DateTime> NgaySinh { get; set; }
    }
}
